"""Reusable configuration constants for the backend."""

DEFAULT_EXCHANGE = "NSE"
DEFAULT_CURRENCY = "INR"
DEFAULT_COUNTRY = "India"

MARKET_PROVIDER_YAHOO = "yahoo"
MARKET_PROVIDER_NSE = "nse"
MARKET_PROVIDER_UPSTOX = "upstox"
MARKET_PROVIDER_ZERODHA = "zerodha"

DEFAULT_MARKET_PROVIDER = MARKET_PROVIDER_YAHOO
DEFAULT_REQUEST_TIMEOUT = 30
DEFAULT_YAHOO_CACHE_TTL = 300
DEFAULT_ENABLE_PROVIDER_CACHE = True
DEFAULT_LOG_PROVIDER_REQUESTS = False
DEFAULT_TIMEZONE = "Asia/Kolkata"

SUPPORTED_MARKET_PROVIDERS = (
    MARKET_PROVIDER_YAHOO,
    MARKET_PROVIDER_NSE,
    MARKET_PROVIDER_UPSTOX,
    MARKET_PROVIDER_ZERODHA,
)
