from abc import ABC, abstractmethod
from typing import Any

from app.domain.signals import Signal
from app.domain.types import UUIDType


class StrategyRepository(ABC):
    """Persistence contract for strategy definitions and generated signals."""

    @abstractmethod
    async def get_definition(self, strategy_id: UUIDType) -> dict[str, Any]:
        """Return a stored JSON strategy definition."""

    @abstractmethod
    async def save_signal(self, signal: Signal) -> None:
        """Persist a normalized signal object."""

    @abstractmethod
    async def get_signals(self, strategy_id: UUIDType) -> tuple[Signal, ...]:
        """Return normalized signals generated by a strategy."""
