from __future__ import annotations

from datetime import UTC, datetime
from decimal import Decimal
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


class Signal(BaseModel):
    """A trading signal generated by a strategy."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    strategy_id: str
    symbol: str
    side: Literal["buy", "sell"]
    confidence: Decimal
    entry_price: Decimal | None = None
    stop_loss: Decimal | None = None
    target: Decimal | None = None
    generated_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    signal_type: str

    @field_validator("generated_at", mode="before")
    @classmethod
    def ensure_timezone(cls, value: object) -> datetime:
        if isinstance(value, datetime):
            if value.tzinfo is None:
                raise ValueError("generated_at must be timezone-aware")
            return value.astimezone(UTC)
        if isinstance(value, str):
            parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
            if parsed.tzinfo is None:
                raise ValueError("generated_at must be timezone-aware")
            return parsed.astimezone(UTC)
        raise TypeError("generated_at must be a datetime")
